[package]
name = "serde-spanned"
version = "0.1.0"
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.125", default-features = false }

[dev-dependencies]
serde_derive = "1.0.125"
